# Generated by Django 3.0.5 on 2020-05-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('blog_name', models.CharField(max_length=255)),
                ('post_url', models.URLField()),
                ('type', models.CharField(choices=[('Text', 'text'), ('Quote', 'quote'), ('Link', 'link'), ('Answer', 'answer'), ('Video', 'video'), ('Audio', 'audio'), ('Photo', 'photo'), ('Chat', 'chat')], max_length=6)),
                ('timestamp', models.IntegerField()),
                ('date', models.DateField()),
                ('mobile', models.BooleanField()),
                ('is_reblog', models.BooleanField()),
                ('note_count', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
                ('tags', models.ManyToManyField(to='tumblr_posts.Tag')),
            ],
        ),
    ]
