# Generated by Django 3.0.5 on 2020-05-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumblr_posts', '0003_auto_20200510_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='uuid',
            field=models.CharField(default='stub', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(max_length=255),
        ),
    ]
