# Generated by Django 3.0.5 on 2020-05-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumblr_posts', '0004_auto_20200510_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_url',
            field=models.URLField(max_length=512),
        ),
    ]
