# Generated by Django 3.0.5 on 2020-05-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tumblr_posts', '0005_auto_20200519_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='blog',
            name='uuid',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
